// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-exporter/models"
)

// GetDevicesReader is a Reader for the GetDevices structure.
type GetDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDevicesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetDevicesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDevicesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDevicesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDevicesOK creates a GetDevicesOK with default headers values
func NewGetDevicesOK() *GetDevicesOK {
	return &GetDevicesOK{}
}

/*
GetDevicesOK describes a response with status code 200, with default header values.

Read-only overview for device list.
*/
type GetDevicesOK struct {
	Payload []*models.DeviceStatusOverview
}

func (o *GetDevicesOK) Error() string {
	return fmt.Sprintf("[GET /devices][%d] getDevicesOK  %+v", 200, o.Payload)
}
func (o *GetDevicesOK) GetPayload() []*models.DeviceStatusOverview {
	return o.Payload
}

func (o *GetDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesBadRequest creates a GetDevicesBadRequest with default headers values
func NewGetDevicesBadRequest() *GetDevicesBadRequest {
	return &GetDevicesBadRequest{}
}

/*
GetDevicesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetDevicesBadRequest struct {
	Payload *models.Error
}

func (o *GetDevicesBadRequest) Error() string {
	return fmt.Sprintf("[GET /devices][%d] getDevicesBadRequest  %+v", 400, o.Payload)
}
func (o *GetDevicesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesUnauthorized creates a GetDevicesUnauthorized with default headers values
func NewGetDevicesUnauthorized() *GetDevicesUnauthorized {
	return &GetDevicesUnauthorized{}
}

/*
GetDevicesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetDevicesUnauthorized struct {
	Payload *models.Error
}

func (o *GetDevicesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /devices][%d] getDevicesUnauthorized  %+v", 401, o.Payload)
}
func (o *GetDevicesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesForbidden creates a GetDevicesForbidden with default headers values
func NewGetDevicesForbidden() *GetDevicesForbidden {
	return &GetDevicesForbidden{}
}

/*
GetDevicesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetDevicesForbidden struct {
	Payload *models.Error
}

func (o *GetDevicesForbidden) Error() string {
	return fmt.Sprintf("[GET /devices][%d] getDevicesForbidden  %+v", 403, o.Payload)
}
func (o *GetDevicesForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesInternalServerError creates a GetDevicesInternalServerError with default headers values
func NewGetDevicesInternalServerError() *GetDevicesInternalServerError {
	return &GetDevicesInternalServerError{}
}

/*
GetDevicesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetDevicesInternalServerError struct {
	Payload *models.Error
}

func (o *GetDevicesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /devices][%d] getDevicesInternalServerError  %+v", 500, o.Payload)
}
func (o *GetDevicesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
