// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ffddorf/unms-exporter/models"
)

// GetDevicesIDStatisticsReader is a Reader for the GetDevicesIDStatistics structure.
type GetDevicesIDStatisticsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDevicesIDStatisticsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDevicesIDStatisticsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDevicesIDStatisticsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetDevicesIDStatisticsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDevicesIDStatisticsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDevicesIDStatisticsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDevicesIDStatisticsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /devices/{id}/statistics] getDevicesIdStatistics", response, response.Code())
	}
}

// NewGetDevicesIDStatisticsOK creates a GetDevicesIDStatisticsOK with default headers values
func NewGetDevicesIDStatisticsOK() *GetDevicesIDStatisticsOK {
	return &GetDevicesIDStatisticsOK{}
}

/*
GetDevicesIDStatisticsOK describes a response with status code 200, with default header values.

Successful
*/
type GetDevicesIDStatisticsOK struct {
	Payload *models.DeviceStatistics
}

// IsSuccess returns true when this get devices Id statistics o k response has a 2xx status code
func (o *GetDevicesIDStatisticsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get devices Id statistics o k response has a 3xx status code
func (o *GetDevicesIDStatisticsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get devices Id statistics o k response has a 4xx status code
func (o *GetDevicesIDStatisticsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get devices Id statistics o k response has a 5xx status code
func (o *GetDevicesIDStatisticsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get devices Id statistics o k response a status code equal to that given
func (o *GetDevicesIDStatisticsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get devices Id statistics o k response
func (o *GetDevicesIDStatisticsOK) Code() int {
	return 200
}

func (o *GetDevicesIDStatisticsOK) Error() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsOK  %+v", 200, o.Payload)
}

func (o *GetDevicesIDStatisticsOK) String() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsOK  %+v", 200, o.Payload)
}

func (o *GetDevicesIDStatisticsOK) GetPayload() *models.DeviceStatistics {
	return o.Payload
}

func (o *GetDevicesIDStatisticsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceStatistics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesIDStatisticsBadRequest creates a GetDevicesIDStatisticsBadRequest with default headers values
func NewGetDevicesIDStatisticsBadRequest() *GetDevicesIDStatisticsBadRequest {
	return &GetDevicesIDStatisticsBadRequest{}
}

/*
GetDevicesIDStatisticsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetDevicesIDStatisticsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get devices Id statistics bad request response has a 2xx status code
func (o *GetDevicesIDStatisticsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get devices Id statistics bad request response has a 3xx status code
func (o *GetDevicesIDStatisticsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get devices Id statistics bad request response has a 4xx status code
func (o *GetDevicesIDStatisticsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get devices Id statistics bad request response has a 5xx status code
func (o *GetDevicesIDStatisticsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get devices Id statistics bad request response a status code equal to that given
func (o *GetDevicesIDStatisticsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get devices Id statistics bad request response
func (o *GetDevicesIDStatisticsBadRequest) Code() int {
	return 400
}

func (o *GetDevicesIDStatisticsBadRequest) Error() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDevicesIDStatisticsBadRequest) String() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsBadRequest  %+v", 400, o.Payload)
}

func (o *GetDevicesIDStatisticsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesIDStatisticsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesIDStatisticsUnauthorized creates a GetDevicesIDStatisticsUnauthorized with default headers values
func NewGetDevicesIDStatisticsUnauthorized() *GetDevicesIDStatisticsUnauthorized {
	return &GetDevicesIDStatisticsUnauthorized{}
}

/*
GetDevicesIDStatisticsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetDevicesIDStatisticsUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get devices Id statistics unauthorized response has a 2xx status code
func (o *GetDevicesIDStatisticsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get devices Id statistics unauthorized response has a 3xx status code
func (o *GetDevicesIDStatisticsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get devices Id statistics unauthorized response has a 4xx status code
func (o *GetDevicesIDStatisticsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get devices Id statistics unauthorized response has a 5xx status code
func (o *GetDevicesIDStatisticsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get devices Id statistics unauthorized response a status code equal to that given
func (o *GetDevicesIDStatisticsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get devices Id statistics unauthorized response
func (o *GetDevicesIDStatisticsUnauthorized) Code() int {
	return 401
}

func (o *GetDevicesIDStatisticsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetDevicesIDStatisticsUnauthorized) String() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetDevicesIDStatisticsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesIDStatisticsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesIDStatisticsForbidden creates a GetDevicesIDStatisticsForbidden with default headers values
func NewGetDevicesIDStatisticsForbidden() *GetDevicesIDStatisticsForbidden {
	return &GetDevicesIDStatisticsForbidden{}
}

/*
GetDevicesIDStatisticsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetDevicesIDStatisticsForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this get devices Id statistics forbidden response has a 2xx status code
func (o *GetDevicesIDStatisticsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get devices Id statistics forbidden response has a 3xx status code
func (o *GetDevicesIDStatisticsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get devices Id statistics forbidden response has a 4xx status code
func (o *GetDevicesIDStatisticsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get devices Id statistics forbidden response has a 5xx status code
func (o *GetDevicesIDStatisticsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get devices Id statistics forbidden response a status code equal to that given
func (o *GetDevicesIDStatisticsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get devices Id statistics forbidden response
func (o *GetDevicesIDStatisticsForbidden) Code() int {
	return 403
}

func (o *GetDevicesIDStatisticsForbidden) Error() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsForbidden  %+v", 403, o.Payload)
}

func (o *GetDevicesIDStatisticsForbidden) String() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsForbidden  %+v", 403, o.Payload)
}

func (o *GetDevicesIDStatisticsForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesIDStatisticsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesIDStatisticsNotFound creates a GetDevicesIDStatisticsNotFound with default headers values
func NewGetDevicesIDStatisticsNotFound() *GetDevicesIDStatisticsNotFound {
	return &GetDevicesIDStatisticsNotFound{}
}

/*
GetDevicesIDStatisticsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetDevicesIDStatisticsNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get devices Id statistics not found response has a 2xx status code
func (o *GetDevicesIDStatisticsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get devices Id statistics not found response has a 3xx status code
func (o *GetDevicesIDStatisticsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get devices Id statistics not found response has a 4xx status code
func (o *GetDevicesIDStatisticsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get devices Id statistics not found response has a 5xx status code
func (o *GetDevicesIDStatisticsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get devices Id statistics not found response a status code equal to that given
func (o *GetDevicesIDStatisticsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get devices Id statistics not found response
func (o *GetDevicesIDStatisticsNotFound) Code() int {
	return 404
}

func (o *GetDevicesIDStatisticsNotFound) Error() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsNotFound  %+v", 404, o.Payload)
}

func (o *GetDevicesIDStatisticsNotFound) String() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsNotFound  %+v", 404, o.Payload)
}

func (o *GetDevicesIDStatisticsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesIDStatisticsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesIDStatisticsInternalServerError creates a GetDevicesIDStatisticsInternalServerError with default headers values
func NewGetDevicesIDStatisticsInternalServerError() *GetDevicesIDStatisticsInternalServerError {
	return &GetDevicesIDStatisticsInternalServerError{}
}

/*
GetDevicesIDStatisticsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetDevicesIDStatisticsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get devices Id statistics internal server error response has a 2xx status code
func (o *GetDevicesIDStatisticsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get devices Id statistics internal server error response has a 3xx status code
func (o *GetDevicesIDStatisticsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get devices Id statistics internal server error response has a 4xx status code
func (o *GetDevicesIDStatisticsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get devices Id statistics internal server error response has a 5xx status code
func (o *GetDevicesIDStatisticsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get devices Id statistics internal server error response a status code equal to that given
func (o *GetDevicesIDStatisticsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get devices Id statistics internal server error response
func (o *GetDevicesIDStatisticsInternalServerError) Code() int {
	return 500
}

func (o *GetDevicesIDStatisticsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDevicesIDStatisticsInternalServerError) String() string {
	return fmt.Sprintf("[GET /devices/{id}/statistics][%d] getDevicesIdStatisticsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDevicesIDStatisticsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDevicesIDStatisticsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
