name: Container Image

on:
  push:
  pull_request_target:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-20.04

    # run on same-repo pushes or forks
    # this avoids running the action twice for
    # pull requests from same-repo branches
    if: ${{ github.event_name == 'push' || github.repository != github.event.repository.full_name }}

    steps:
      - name: Compute Labels
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/ffddorf/unms-exporter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ffddorf+github_actions
          password: ${{ secrets.QUAY_BOT_PASSWORD }}
      - name: Build Image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Build Image for fork PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/${{ github.event.repository.full_name }}.git#${{ github.event.pull_request.head.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
