name: Container Image

on: push

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Compute Labels
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/ffddorf/unms-exporter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ffddorf+github_actions
          password: ${{ secrets.QUAY_BOT_PASSWORD }}
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
