// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Antenna antenna
//
// swagger:model antenna
type Antenna struct {

	// gain
	Gain float64 `json:"gain,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this antenna
func (m *Antenna) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this antenna based on context it is used
func (m *Antenna) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Antenna) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Antenna) UnmarshalBinary(b []byte) error {
	var res Antenna
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
