// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Antenna1 antenna 1
//
// swagger:model antenna 1
type Antenna1 struct {

	// cable loss
	CableLoss float64 `json:"cableLoss,omitempty"`

	// gain
	Gain float64 `json:"gain,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this antenna 1
func (m *Antenna1) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this antenna 1 based on context it is used
func (m *Antenna1) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Antenna1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Antenna1) UnmarshalBinary(b []byte) error {
	var res Antenna1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
