// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Capacities1 capacities 1
//
// swagger:model capacities 1
type Capacities1 []string

var capacities1ItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["auto"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		capacities1ItemsEnum = append(capacities1ItemsEnum, v)
	}
}

func (m *Capacities1) validateCapacities1ItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, capacities1ItemsEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this capacities 1
func (m Capacities1) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		// value enum
		if err := m.validateCapacities1ItemsEnum(strconv.Itoa(i), "body", m[i]); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this capacities 1 based on context it is used
func (m Capacities1) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
