// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CoordinatesXY coordinates x y
//
// swagger:model CoordinatesXY.
type CoordinatesXY struct {

	// x
	X float64 `json:"x,omitempty"`

	// y
	Y float64 `json:"y,omitempty"`
}

// Validate validates this coordinates x y
func (m *CoordinatesXY) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this coordinates x y based on context it is used
func (m *CoordinatesXY) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CoordinatesXY) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CoordinatesXY) UnmarshalBinary(b []byte) error {
	var res CoordinatesXY
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
