// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DfsLockouts DFS lockout frequencies
// Example: [5440,5460]
//
// swagger:model dfsLockouts
type DfsLockouts []float64

// Validate validates this dfs lockouts
func (m DfsLockouts) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dfs lockouts based on context it is used
func (m DfsLockouts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
