// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Discovery discovery
//
// swagger:model discovery
type Discovery struct {

	// configured
	Configured bool `json:"configured,omitempty"`

	// error
	Error string `json:"error,omitempty"`

	// is processing
	IsProcessing bool `json:"isProcessing,omitempty"`

	// protocol
	Protocol string `json:"protocol,omitempty"`

	// snmp community
	SnmpCommunity string `json:"snmpCommunity,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// visible by
	VisibleBy *VisibleBy `json:"visibleBy,omitempty"`
}

// Validate validates this discovery
func (m *Discovery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVisibleBy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Discovery) validateVisibleBy(formats strfmt.Registry) error {
	if swag.IsZero(m.VisibleBy) { // not required
		return nil
	}

	if m.VisibleBy != nil {
		if err := m.VisibleBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("visibleBy")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this discovery based on the context it is used
func (m *Discovery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateVisibleBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Discovery) contextValidateVisibleBy(ctx context.Context, formats strfmt.Registry) error {

	if m.VisibleBy != nil {
		if err := m.VisibleBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("visibleBy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Discovery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Discovery) UnmarshalBinary(b []byte) error {
	var res Discovery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
