// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InterfaceOspf interface ospf
//
// swagger:model InterfaceOspf
type InterfaceOspf struct {

	// ospf capable
	// Example: true
	OspfCapable bool `json:"ospfCapable,omitempty"`

	// ospf config
	// Required: true
	OspfConfig *OspfConfig `json:"ospfConfig"`
}

// Validate validates this interface ospf
func (m *InterfaceOspf) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOspfConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InterfaceOspf) validateOspfConfig(formats strfmt.Registry) error {

	if err := validate.Required("ospfConfig", "body", m.OspfConfig); err != nil {
		return err
	}

	if m.OspfConfig != nil {
		if err := m.OspfConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ospfConfig")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this interface ospf based on the context it is used
func (m *InterfaceOspf) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOspfConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InterfaceOspf) contextValidateOspfConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.OspfConfig != nil {
		if err := m.OspfConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ospfConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InterfaceOspf) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InterfaceOspf) UnmarshalBinary(b []byte) error {
	var res InterfaceOspf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
