// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Interval interval
//
// swagger:model interval
type Interval struct {

	// end
	End float64 `json:"end,omitempty"`

	// start
	Start float64 `json:"start,omitempty"`
}

// Validate validates this interval
func (m *Interval) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this interval based on context it is used
func (m *Interval) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Interval) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Interval) UnmarshalBinary(b []byte) error {
	var res Interval
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
