// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InterfaceStatus interface status
//
// swagger:model InterfaceStatus
type InterfaceStatus struct {

	// current speed
	// Example: 1000-full
	CurrentSpeed string `json:"currentSpeed,omitempty"`

	// description
	// Example: 1 Gbps - Full Duplex
	Description string `json:"description,omitempty"`

	// plugged
	// Example: true
	Plugged bool `json:"plugged,omitempty"`

	// speed
	// Example: auto
	Speed string `json:"speed,omitempty"`

	// status
	// Example: active
	Status string `json:"status,omitempty"`
}

// Validate validates this interface status
func (m *InterfaceStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this interface status based on context it is used
func (m *InterfaceStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InterfaceStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InterfaceStatus) UnmarshalBinary(b []byte) error {
	var res InterfaceStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
