// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InterfacePppoe interface pppoe
//
// swagger:model interfacePppoe
type InterfacePppoe struct {

	// account
	Account string `json:"account,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// parent
	Parent string `json:"parent,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this interface pppoe
func (m *InterfacePppoe) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this interface pppoe based on context it is used
func (m *InterfacePppoe) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InterfacePppoe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InterfacePppoe) UnmarshalBinary(b []byte) error {
	var res InterfacePppoe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
