// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// LoadBalanceValues load balance values
//
// swagger:model loadBalanceValues
type LoadBalanceValues []string

// Validate validates this load balance values
func (m LoadBalanceValues) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this load balance values based on context it is used
func (m LoadBalanceValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
