// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Model2 model 2
//
// swagger:model Model 2
type Model2 struct {

	// cidr
	// Example: 192.168.1.100/24
	// Required: true
	Cidr *string `json:"cidr"`

	// origin
	// Example: dhcp
	// Enum: [dhcp slaac link-local static]
	Origin string `json:"origin,omitempty"`

	// type
	// Example: dynamic
	// Required: true
	// Enum: [dynamic static dhcp dhcpv6]
	Type *string `json:"type"`

	// version
	// Example: v4
	// Enum: [v4 v6]
	Version string `json:"version,omitempty"`
}

// Validate validates this model 2
func (m *Model2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCidr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrigin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Model2) validateCidr(formats strfmt.Registry) error {

	if err := validate.Required("cidr", "body", m.Cidr); err != nil {
		return err
	}

	return nil
}

var model2TypeOriginPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dhcp","slaac","link-local","static"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		model2TypeOriginPropEnum = append(model2TypeOriginPropEnum, v)
	}
}

const (

	// Model2OriginDhcp captures enum value "dhcp"
	Model2OriginDhcp string = "dhcp"

	// Model2OriginSlaac captures enum value "slaac"
	Model2OriginSlaac string = "slaac"

	// Model2OriginLinkMinuslocal captures enum value "link-local"
	Model2OriginLinkMinuslocal string = "link-local"

	// Model2OriginStatic captures enum value "static"
	Model2OriginStatic string = "static"
)

// prop value enum
func (m *Model2) validateOriginEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, model2TypeOriginPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Model2) validateOrigin(formats strfmt.Registry) error {
	if swag.IsZero(m.Origin) { // not required
		return nil
	}

	// value enum
	if err := m.validateOriginEnum("origin", "body", m.Origin); err != nil {
		return err
	}

	return nil
}

var model2TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dynamic","static","dhcp","dhcpv6"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		model2TypeTypePropEnum = append(model2TypeTypePropEnum, v)
	}
}

const (

	// Model2TypeDynamic captures enum value "dynamic"
	Model2TypeDynamic string = "dynamic"

	// Model2TypeStatic captures enum value "static"
	Model2TypeStatic string = "static"

	// Model2TypeDhcp captures enum value "dhcp"
	Model2TypeDhcp string = "dhcp"

	// Model2TypeDhcpv6 captures enum value "dhcpv6"
	Model2TypeDhcpv6 string = "dhcpv6"
)

// prop value enum
func (m *Model2) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, model2TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Model2) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

var model2TypeVersionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["v4","v6"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		model2TypeVersionPropEnum = append(model2TypeVersionPropEnum, v)
	}
}

const (

	// Model2VersionV4 captures enum value "v4"
	Model2VersionV4 string = "v4"

	// Model2VersionV6 captures enum value "v6"
	Model2VersionV6 string = "v6"
)

// prop value enum
func (m *Model2) validateVersionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, model2TypeVersionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Model2) validateVersion(formats strfmt.Registry) error {
	if swag.IsZero(m.Version) { // not required
		return nil
	}

	// value enum
	if err := m.validateVersionEnum("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this model 2 based on context it is used
func (m *Model2) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Model2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Model2) UnmarshalBinary(b []byte) error {
	var res Model2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
