// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Parent1 parent 1
//
// swagger:model parent 1
type Parent1 interface{}
