// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PingWatchdog ping watchdog
//
// swagger:model pingWatchdog
type PingWatchdog struct {

	// Custom IP address in IPv4 or IPv6 format.
	// Example: 192.168.1.22
	Address string `json:"address,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// failure count
	FailureCount float64 `json:"failureCount,omitempty"`

	// interval
	Interval float64 `json:"interval,omitempty"`

	// off delay
	OffDelay float64 `json:"offDelay,omitempty"`

	// start delay
	StartDelay float64 `json:"startDelay,omitempty"`
}

// Validate validates this ping watchdog
func (m *PingWatchdog) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ping watchdog based on context it is used
func (m *PingWatchdog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PingWatchdog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PingWatchdog) UnmarshalBinary(b []byte) error {
	var res PingWatchdog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
