// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Prerelease prerelease
//
// swagger:model prerelease
type Prerelease []string

// Validate validates this prerelease
func (m Prerelease) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prerelease based on context it is used
func (m Prerelease) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
