// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TxChain Wireless signal level in dBm for each antenna chain.
// Example: [30,40]
//
// swagger:model txChain
type TxChain []int64

// Validate validates this tx chain
func (m TxChain) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tx chain based on context it is used
func (m TxChain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
