// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Vlans vlans
//
// swagger:model vlans
type Vlans struct {

	// interface
	Interface Interface `json:"interface,omitempty"`

	// vlan Id
	VlanID Interface `json:"vlanId,omitempty"`
}

// Validate validates this vlans
func (m *Vlans) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vlans based on context it is used
func (m *Vlans) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Vlans) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Vlans) UnmarshalBinary(b []byte) error {
	var res Vlans
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
